MODEL:
  NAME: "deeplabv3plus_resnet101"  # deeplabv2_resnet101 & deeplabv3plus_resnet101
  WEIGHTS: "https://download.pytorch.org/models/resnet101-5d3b4d8f.pth"
  FREEZE_BN: True
  NUM_CLASSES: 19
DATASETS:
  SOURCE_TRAIN: "gtav_train"   # gtav_train and synthia_train
  TARGET_TRAIN: "cityscapes_train"
  TEST: "cityscapes_val"
INPUT:
  SOURCE_INPUT_SIZE_TRAIN: (1280, 720)
  TARGET_INPUT_SIZE_TRAIN: (1280, 640)
  INPUT_SIZE_TEST: (1280, 640)
SOLVER:
  BASE_LR: 1.0e-5
  MAX_ITER: 1000
  STOP_ITER: 1000
  WARMUP_ITER: 10000
  BATCH_SIZE: 2
  CONSISTENT_LOSS: 0.1
  NEGATIVE_LOSS: 1.0
  NEGATIVE_THRESHOLD: 0.05
LOSS:
  TEMPERATURE: 0.05
  POS_WEIGHT_INCRE_STEP: 0.02
  NEG_WEIGHT_INCRE_STEP: 0.02
ACTIVE:
  NAME: 'RCL-AAA'
  SETTING: 'RA'
  SELECT_ITER: [10000, 12000, 14000, 16000, 18000]
  RATIO: 0.05
  RADIUS_K: 1
